- name: create directory for alphafold
  file:
    path: /opt/alphafold
    state: directory
    owner: alphafold

- name: mount /dev/sdb1 to /opt/alphafold
  mount:
    path: "/opt/alphafold"
    src: "/dev/sdb1"
    fstype: ext4 
    state: mounted

- name: install nfs-kernel-server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: set export directory
  lineinfile:
    dest: /etc/exports
    line: '/opt/alphafold 192.168.2.0/255.255.255.0(rw,sync,no_subtree_check,no_root_squash)'
    insertbefore: EOF
    state: present
