- name: copy a .deb files
  copy:
    dest: /tmp/cuda.deb
    src: "cuda-repo-{{ deb_version }}_amd64.deb"

- name: install a .deb package
  apt:
    deb: "/tmp/cuda.deb"

- name: copy the kering file to the /usr/share/keyring directory
  copy:
    src: "/var/cuda-repo-{{ cuda_version }}/cuda-{{ key_version }}-keyring.gpg"
    dest: "/usr/share/keyrings/cuda-{{ key_version }}-keyring.gpg"
    remote_src: yes

- name: install cuda
  apt:
    name: cuda
    state: present
    update_cache: yes
  notify: reboot the machine

- name: upgrade cuda
  apt:
    name: cuda
    state: latest
    update_cache: yes
  notify: reboot the machine

- meta: flush_handlers
