- name: copy a .deb files
  copy:
    dest: /tmp/cuda.deb
    src: "cuda-repo-{{ deb_version }}_amd64.deb"

- name: install a .deb package
  apt:
    deb: "/tmp/cuda.deb"

- name: copy the keyring file to the /usr/share/keyring directory
  copy:
    src: "{{ item }}"
    dest: "/usr/share/keyrings/"
    with_fileglob:
        - "/var/cuda-repo-{{ deb_version }}-local/cuda-*-keyring.gpg"

- name: install cuda
  apt:
    name: cuda
    state: present
    update_cache: yes
  notify: reboot the machine

- name: upgrade cuda
  apt:
    name: cuda
    state: latest
    update_cache: yes
  notify: reboot the machine

- meta: flush_handlers
