- name: copy a .deb files
  copy:
    dest: /tmp/cuda.deb
    src: "cuda-repo-{{ deb_version }}_amd64.deb"

- name: install a .deb package
  apt:
    deb: "/tmp/cuda.deb"

- name: add an apt key
  apt_key:
    file: "/var/cuda-repo-{{ cuda_version }}/7fa2af80.pub"

- name: install cuda
  apt:
    name: cuda-11-4
    state: present
    update_cache: yes
  notify: reboot the machine

#- name: upgrade cuda
#  apt:
#    name: cuda
#    state: latest
#    update_cache: yes
#  notify: reboot the machine

- meta: flush_handlers
