- name: change archive servers to those in Japan
  replace:
    dest: /etc/apt/sources.list
    regexp: 'deb https?://[^(security)]\S* (.*)'
    replace: 'deb http://jp.archive.ubuntu.com/ubuntu \1'

- command: grep -e "\<universe\>" /etc/apt/sources.list
  register: check_universe_repo
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: add the universe repository
  command: add-apt-repository universe && apt-get update
  when: check_universe_repo.rc != 0

- name: disable unattended upgrades 
  lineinfile:
    path:   "/etc/apt/apt.conf.d/20auto-upgrades"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line}}"
  with_items:
    - { regexp: 'Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "0";' }
    - { regexp: 'Unattended-Upgrade',   line: 'APT::Periodic::Unattended-Upgrade "0";' }
