- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: configure /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.2.200 GolgiAdmin GolgiAdmin.golgi
      192.168.2.201 GolgiFS

- name: link python to python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: disable suspend mode
  command: "sudo systemctl mask sleep.target suspend.target. hibernate.target hybrid-sleep.target"

- name: install zsh
  apt:
    name: zsh
    state: present

