- name: install some packages
  apt:
    name: ["apt-transport-https", "ca-certificates", "software-properties-common"]
    state: present
    update_cache: yes

- name: add an apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add a docker stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  apt:
    name: docker-ce
    update_cache: yes

- name: add an apt key for nvidia-docker
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
  tags:
    - nvidia-docker

- name: add apt repositories
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/ubuntu{{ ansible_distribution_version }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  tags:
    - nvidia-docker

- name: install nvidia-docker
  apt:
    name: nvidia-docker2
    update_cache: yes
  notify: restart docker daemon
  tags:
    - nvidia-docker
