- name: install nis package
  apt:
    name: nis
    state: present
    update_cache: yes
  notify: restart nis

- name: set defaultdomain
  copy:
    dest: /etc/defaultdomain
    content: "{{ domain }}"
  notify: restart nis

- name: configure /etc/default/nis
  replace:
    path: /etc/default/nis
    regexp: '^NISSERVER=false'
    replace: 'NISSERVER=master'

- name: remove all IP accept setting for admin node
  replace:
    path: /etc/ypserv.securenets
    regexp: '^0.0.0.0         0.0.0.0'
    replace: '#0.0.0.0         0.0.0.0'
  notify: restart nis

- name: add IP range restriction for admin node
  lineinfile:
    path: /etc/ypserv.securenets
    insertafter: '^#0.0.0.0'
    line: '255.255.255.0         192.168.2.0'
  notify: restart nis

- meta: flush_handlers

- name: install pip3 to install pexpect
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: set domainname
  command: "domainname {{ domain }}"

- name: install pexpect for ypinit
  pip:
    name: pexpect
  become: yes

- name: excute ypinit
  expect:
    command: /usr/lib/yp/ypinit -m
    responses:
      "^.*next host to add:": "\x04"
      "^Is this correct?.*[y/n: y]": "y"

- name: modify MINGID in yp Makefile
  lineinfile:
    path: /var/yp/Makefile
    regexp: '^MINGID='
    line: 'MINGID=999'
