- name: copy a .deb files
  copy:
    dest: /tmp/cuda.deb
    src: "cuda-repo-{{ deb_version }}_amd64.deb"

- name: install a .deb package
  apt:
    deb: "/tmp/cuda.deb"

- name: add an apt key
  apt_key:
    file: "/var/cuda-repo-{{ apt_key_version }}/7fa2af80.pub"

- name: install cuda
  apt:
    name: cuda
    state: present
    update_cache: yes
  notify: reboot the machine

- name: copy patches .deb files
  copy:
    dest: "/tmp/{{ item }}"
    src: "{{ item }}"
  with_items:
    - "cuda-repo-{{ patch_prefix }}.1-1_amd64.deb"
    - "cuda-repo-{{ patch_prefix }}.2-1_amd64.deb"

- name: install patches .deb packages
  apt:
    deb: "/tmp/{{ item }}"
    force: yes
  with_items:
    - "cuda-repo-{{ patch_prefix }}.1-1_amd64.deb"
    - "cuda-repo-{{ patch_prefix }}.2-1_amd64.deb"

- name: upgrade cuda
  apt:
    name: cuda
    state: latest
    update_cache: yes
  notify: reboot the machine

- meta: flush_handlers
