- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: disable suspend mode
  file:
    src: /dev/null
    dest: "{{ item }}"
    state: link
  with_items:
      - /etc/systemd/system/sleep.target
      - /etc/systemd/system/suspend.target
      - /etc/systemd/system/hibernate.target
      - /etc/systemd/system/hybrid-sleep.target

- name: configure /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.2.200 GolgiAdmin GolgiAdmin.golgi
      192.168.2.201 GolgiFS

      192.168.2.1 Golgi01 golgi01
      192.168.2.2 Golgi02 golgi02
      192.168.2.3 Golgi03 golgi03
      192.168.2.4 Golgi04 golgi04
      192.168.2.5 Golgi05 golgi05
      192.168.2.6 Golgi06 golgi06
      192.168.2.7 Golgi07 golgi07
      192.168.2.8 Golgi08 golgi08
      192.168.2.9 Golgi09 golgi09
      192.168.2.10 Golgi10 golgi10
      192.168.2.11 Golgi11 golgi11
      192.168.2.12 Golgi12 golgi12
      192.168.2.13 Golgi13 golgi13
      192.168.2.14 Golgi14 golgi14
      192.168.2.15 Golgi15 golgi15

- name: copy script for admin
  copy:
    src: "{{ item }}"
    dest: "/root/sbin/{{ item }}"
    owner: root
    group: root
  with_items:
    - do_all
    - shutdown_all

- name: IP forwarding setup
  replace:
    path: /etc/sysctl.conf
    regexp: "^#net.ipv4.ip_forward=1"
    replace: "net.ipv4.ip_forward=1"

- name: set iptables.rules
  copy:
    dest: /etc/iptables.rules
    src: iptables.rules

- name: enable to restore iptables setting durint start-up
  copy:
    dest: /etc/network/if-pre-up.d/iptables-restore
    src: iptables-restore
    mode: '755'

- name: install ifupdown for iptables setting during start-up
  apt:
    name: ifupdown
    state: present

- name: install zsh
  apt:
    name: zsh
    state: present

- name: install packages for golgi temperature
  apt:
    name: ["parallel", "moreutils"]
    state: present
