- name: install MUNGE
  apt:
    name: ["munge", "libmunge-dev"]
    state: present
  notify: restart munge

- name: copy munge.key
  copy:
    dest: /etc/munge/munge.key
    src: munge.key
  notify: restart munge

