- name: install fftw and cmake
  apt:
    name: ["libfftw3-dev", "cmake"]
    state: present

- stat:
    path: "{{ install_prefix }}-{{ version }}/bin/gmx"
  register: gmx_result

- name: ensure a source directory exists
  file:
    path: "{{ source_directory }}"
    state: directory

- name: unarchive source files
  unarchive:
    src: "gromacs-{{ version }}.tar.gz"
    dest: "{{ source_directory }}"
  when: not gmx_result.stat.exists

- name: fix cmake
  lineinfile:
    path: "{{ source_directory }}/gromacs-{{ version }}/cmake/gmxManageNvccConfig.cmake"
    regexp: '(.*arch=compute_20,code=sm_20.*)'
    state: absent
  when: not gmx_result.stat.exists

- name: create builddir
  tempfile:
    state: directory
    suffix: gromacs-build
  register: builddir
  when: not gmx_result.stat.exists

- name: configure
  command: "cmake {{ source_directory }}/gromacs-{{ version }} -DGMX_SIMD=AVX2_256 -DGMX_GPU=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DREGRESSIONTEST_DOWNLOAD=ON -DCMAKE_INSTALL_PREFIX={{ install_prefix }}-{{ version }}"
  args:
    chdir: "{{ builddir.path }}"
  when: not gmx_result.stat.exists

- name: compile, test and install
  make:
    target: "{{ item }}"
    chdir: "{{ builddir.path }}"
  with_items:
    - all
    - check
    - install
  when: not gmx_result.stat.exists

- name: clear builddir
  file:
    path: "{{ builddir.path }}"
    state: absent
  when: not gmx_result.stat.exists
